services:
  - mongodb
  - rabbitmq

sudo: required

language: java

jdk:
  - oraclejdk8

install: true

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

script: ./gradlew check

after_success:
- ./gradlew cobertura coveralls

deploy:
- ./gradlew uploadArchives